import { ArrowForward } from "../wrapped-icons/navigation/ArrowForward";
import { ArrowBackThick } from "../wrapped-icons/navigation/ArrowBackThick";
import { ArrowBack } from "../wrapped-icons/navigation/ArrowBack";
import { ArrowBackThickFill } from "../wrapped-icons/navigation/ArrowBackThickFill";
import { ArrowClockwise } from "../wrapped-icons/navigation/ArrowClockwise";
import { ArrowCounterClockwise } from "../wrapped-icons/navigation/ArrowCounterClockwise";
import { ArrowCycle } from "../wrapped-icons/navigation/ArrowCycle";
import { ArrowDown } from "../wrapped-icons/navigation/ArrowDown";
import { ArrowDownLeft } from "../wrapped-icons/navigation/ArrowDownLeft";
import { ArrowDownRight } from "../wrapped-icons/navigation/ArrowDownRight";
import { ArrowDownThick } from "../wrapped-icons/navigation/ArrowDownThick";
import { ArrowEnlarge } from "../wrapped-icons/navigation/ArrowEnlarge";
import { ArrowUpThick } from "../wrapped-icons/navigation/ArrowUpThick";
import { ArrowUpRight } from "../wrapped-icons/navigation/ArrowUpRight";
import { ArrowForwardThick } from "../wrapped-icons/navigation/ArrowForwardThick";
import { ArrowForwardThickFill } from "../wrapped-icons/navigation/ArrowForwardThickFill";
import { ArrowLeft } from "../wrapped-icons/navigation/ArrowLeft";
import { ArrowLeftThick } from "../wrapped-icons/navigation/ArrowLeftThick";
import { ArrowUpLeft } from "../wrapped-icons/navigation/ArrowUpLeft";
import { ArrowUpDown } from "../wrapped-icons/navigation/ArrowUpDown";
import { ArrowUp } from "../wrapped-icons/navigation/ArrowUp";
import { ArrowShuffle } from "../wrapped-icons/navigation/ArrowShuffle";
import { ArrowRightThick } from "../wrapped-icons/navigation/ArrowRightThick";
import { ArrowRightLeft } from "../wrapped-icons/navigation/ArrowRightLeft";
import { ArrowRight } from "../wrapped-icons/navigation/ArrowRight";
import { ArrowRepeat } from "../wrapped-icons/navigation/ArrowRepeat";
import { Box } from "../wrapped-icons/shapes/Box";
import { DotGrid } from "../wrapped-icons/navigation/DotGrid";
import { DragHorizontal } from "../wrapped-icons/navigation/DragHorizontal";
import { DragVertical } from "../wrapped-icons/navigation/DragVertical";
import { ArrowHeight } from "../wrapped-icons/navigation/ArrowHeight";
import { ForkLeft } from "../wrapped-icons/navigation/ForkLeft";
import { ForkRight } from "../wrapped-icons/navigation/ForkRight";
import { FullScreen } from "../wrapped-icons/navigation/FullScreen";
import { Grid } from "../wrapped-icons/navigation/Grid";

const NavigationIconCollection = new Map();
// Error State Box
NavigationIconCollection.set("Empty", Box);

NavigationIconCollection.set("ArrowBack", ArrowBack);
NavigationIconCollection.set("ArrowBackThick", ArrowBackThick);
NavigationIconCollection.set("ArrowBackThickFilled", ArrowBackThickFill);
NavigationIconCollection.set("ArrowClockwise", ArrowClockwise);
NavigationIconCollection.set("ArrowCounterClockwise", ArrowCounterClockwise);
NavigationIconCollection.set("ArrowCycle", ArrowCycle);
NavigationIconCollection.set("ArrowDown", ArrowDown);
NavigationIconCollection.set("ArrowDownLeft", ArrowDownLeft);
NavigationIconCollection.set("ArrowDownRight", ArrowDownRight);
NavigationIconCollection.set("ArrowDownThick", ArrowDownThick);
NavigationIconCollection.set("ArrowEnlarge", ArrowEnlarge);
NavigationIconCollection.set("ArrowForward", ArrowForward);
NavigationIconCollection.set("ArrowForwardThick", ArrowForwardThick);
NavigationIconCollection.set("ArrowForwardThickFilled", ArrowForwardThickFill);
NavigationIconCollection.set("ArrowLeft", ArrowLeft);
NavigationIconCollection.set("ArrowLeftThick", ArrowLeftThick);
NavigationIconCollection.set("ArrowRepeat", ArrowRepeat);
NavigationIconCollection.set("ArrowRight", ArrowRight);
NavigationIconCollection.set("ArrowRightLeft", ArrowRightLeft);
NavigationIconCollection.set("ArrowRightThick", ArrowRightThick);
NavigationIconCollection.set("ArrowShuffle", ArrowShuffle);
NavigationIconCollection.set("ArrowUpDown", ArrowUpDown);
NavigationIconCollection.set("ArrowUp", ArrowUp);
NavigationIconCollection.set("ArrowUpLeft", ArrowUpLeft);
NavigationIconCollection.set("ArrowUpRight", ArrowUpRight);
NavigationIconCollection.set("ArrowUpThick", ArrowUpThick);
NavigationIconCollection.set("DotGrid", DotGrid);
NavigationIconCollection.set("DragHorizontal", DragHorizontal);
NavigationIconCollection.set("DragVertical", DragVertical);
NavigationIconCollection.set("ArrowHeight", ArrowHeight);
NavigationIconCollection.set("ForkLeft", ForkLeft);
NavigationIconCollection.set("ForkRight", ForkRight);
NavigationIconCollection.set("FullScreen", FullScreen);
NavigationIconCollection.set("Grid", Grid);

export { NavigationIconCollection };
