import { ArrowForward } from "../wrapped-icons/navigation/ArrowForward";
import { AlignBottom } from "../wrapped-icons/navigation/AlignBottom";
import { AlignHorizontalCenter } from "../wrapped-icons/navigation/AlignHorizontalCenter";
import { AlignLeft } from "../wrapped-icons/navigation/AlignLeft";
import { AlignRight } from "../wrapped-icons/navigation/AlignRight";
import { AlignTop } from "../wrapped-icons/navigation/AlignTop";
import { AlignToBottom } from "../wrapped-icons/navigation/AlignToBottom";
import { AlignToMiddle } from "../wrapped-icons/navigation/AlignToMiddle";
import { AlignVerticalCenter } from "../wrapped-icons/navigation/AlignVerticalCenter";
import { ArrowBackThick } from "../wrapped-icons/navigation/ArrowBackThick";
import { ArrowBack } from "../wrapped-icons/navigation/ArrowBack";
import { ArrowBackThickFill } from "../wrapped-icons/navigation/ArrowBackThickFill";
import { ArrowClockwise } from "../wrapped-icons/navigation/ArrowClockwise";
import { ArrowCounterClockwise } from "../wrapped-icons/navigation/ArrowCounterClockwise";
import { ArrowCycle } from "../wrapped-icons/navigation/ArrowCycle";
import { ArrowDown } from "../wrapped-icons/navigation/ArrowDown";
import { ArrowDownLeft } from "../wrapped-icons/navigation/ArrowDownLeft";
import { ArrowDownRight } from "../wrapped-icons/navigation/ArrowDownRight";
import { ArrowDownThick } from "../wrapped-icons/navigation/ArrowDownThick";
import { ArrowUpThick } from "../wrapped-icons/navigation/ArrowUpThick";
import { ArrowUpRight } from "../wrapped-icons/navigation/ArrowUpRight";
import { ArrowForwardThick } from "../wrapped-icons/navigation/ArrowForwardThick";
import { ArrowForwardThickFill } from "../wrapped-icons/navigation/ArrowForwardThickFill";
import { ArrowLeft } from "../wrapped-icons/navigation/ArrowLeft";
import { ArrowLeftThick } from "../wrapped-icons/navigation/ArrowLeftThick";
import { ArrowUpLeft } from "../wrapped-icons/navigation/ArrowUpLeft";
import { ArrowUpDown } from "../wrapped-icons/navigation/ArrowUpDown";
import { ArrowUp } from "../wrapped-icons/navigation/ArrowUp";
import { ArrowShuffle } from "../wrapped-icons/navigation/ArrowShuffle";
import { ArrowRightThick } from "../wrapped-icons/navigation/ArrowRightThick";
import { ArrowRightLeft } from "../wrapped-icons/navigation/ArrowRightLeft";
import { ArrowRight } from "../wrapped-icons/navigation/ArrowRight";
import { ArrowRepeat } from "../wrapped-icons/navigation/ArrowRepeat";
import { AlignToTop } from "../wrapped-icons/navigation/AlignToTop";
import { Box } from "../wrapped-icons/shapes/Box";

const NavigationIconCollection = new Map();
// Error State Box
NavigationIconCollection.set("Empty", Box);

NavigationIconCollection.set("AlignBottom", AlignBottom);
NavigationIconCollection.set("AlignHorizontalCenter", AlignHorizontalCenter);
NavigationIconCollection.set("AlignLeft", AlignLeft);
NavigationIconCollection.set("AlignRight", AlignRight);
NavigationIconCollection.set("AlignToBottom", AlignToBottom);
NavigationIconCollection.set("AlignToMiddle", AlignToMiddle);
NavigationIconCollection.set("AlignTop", AlignTop);
NavigationIconCollection.set("AlignToTop", AlignToTop);
NavigationIconCollection.set("AlignVerticalCenter", AlignVerticalCenter);
NavigationIconCollection.set("ArrowBack", ArrowBack);
NavigationIconCollection.set("ArrowBackThick", ArrowBackThick);
NavigationIconCollection.set("ArrowBackThickFill", ArrowBackThickFill);
NavigationIconCollection.set("ArrowClockwise", ArrowClockwise);
NavigationIconCollection.set("ArrowCounterClockwise", ArrowCounterClockwise);
NavigationIconCollection.set("ArrowCycle", ArrowCycle);
NavigationIconCollection.set("ArrowDown", ArrowDown);
NavigationIconCollection.set("ArrowDownLeft", ArrowDownLeft);
NavigationIconCollection.set("ArrowDownRight", ArrowDownRight);
NavigationIconCollection.set("ArrowDownThick", ArrowDownThick);
NavigationIconCollection.set("ArrowForward", ArrowForward);
NavigationIconCollection.set("ArrowForwardThick", ArrowForwardThick);
NavigationIconCollection.set("ArrowForwardThickFill", ArrowForwardThickFill);
NavigationIconCollection.set("ArrowLeft", ArrowLeft);
NavigationIconCollection.set("ArrowLeftThick", ArrowLeftThick);
NavigationIconCollection.set("ArrowRepeat", ArrowRepeat);
NavigationIconCollection.set("ArrowRight", ArrowRight);
NavigationIconCollection.set("ArrowRightLeft", ArrowRightLeft);
NavigationIconCollection.set("ArrowRightThick", ArrowRightThick);
NavigationIconCollection.set("ArrowShuffle", ArrowShuffle);
NavigationIconCollection.set("ArrowUpDown", ArrowUpDown);
NavigationIconCollection.set("ArrowUp", ArrowUp);
NavigationIconCollection.set("ArrowUpLeft", ArrowUpLeft);
NavigationIconCollection.set("ArrowUpRight", ArrowUpRight);
NavigationIconCollection.set("ArrowUpThick", ArrowUpThick);

export { NavigationIconCollection };
