import { Air } from "../wrapped-icons/generic/Air";
import { Alarm } from "../wrapped-icons/generic/Alarm";
import { AlertCircle } from "../wrapped-icons/generic/AlertCircle";
import { AlertCircleFilled } from "../wrapped-icons/generic/AlertCircleFilled";
import { Arrow } from "../wrapped-icons/generic/Arrow";
import { Attach } from "../wrapped-icons/generic/Attach";
import { Backspace } from "../wrapped-icons/generic/Backspace";
import { BackspaceFill } from "../wrapped-icons/generic/BackspaceFill";
import { Bell } from "../wrapped-icons/generic/Bell";
import { Block } from "../wrapped-icons/generic/Block";
import { Book } from "../wrapped-icons/generic/Book";
import { BookOpen } from "../wrapped-icons/generic/BookOpen";
import { Briefcase } from "../wrapped-icons/generic/Briefcase";
import { Bug } from "../wrapped-icons/generic/Bug";
import { Cake } from "../wrapped-icons/generic/Cake";
import { Calculator } from "../wrapped-icons/generic/Calculator";
import { Calendar } from "../wrapped-icons/generic/Calendar";
import { Camera } from "../wrapped-icons/generic/Camera";
import { Check } from "../wrapped-icons/generic/Check";
import { CheckBox } from "../wrapped-icons/generic/CheckBox";
import { CheckBoxFilled } from "../wrapped-icons/generic/CheckBoxFilled";
import { CheckCircle } from "../wrapped-icons/generic/CheckCircle";
import { CheckCircleFilled } from "../wrapped-icons/generic/CheckCircleFilled";
import { CheckDouble } from "../wrapped-icons/generic/CheckDouble";
import { Chess } from "../wrapped-icons/generic/Chess";
import { Clipboard } from "../wrapped-icons/generic/Clipboard";
import { Clock } from "../wrapped-icons/generic/Clock";
import { Cloud } from "../wrapped-icons/generic/Cloud";
import { Coffee } from "../wrapped-icons/generic/Coffee";
import { CrossedSwords } from "../wrapped-icons/generic/CrossedSwords";
import { Crown } from "../wrapped-icons/generic/Crown";
import { Dice1 } from "../wrapped-icons/generic/Dice1";
import { Dice2 } from "../wrapped-icons/generic/Dice2";
import { Dice3 } from "../wrapped-icons/generic/Dice3";
import { Dice4 } from "../wrapped-icons/generic/Dice4";
import { Dice5 } from "../wrapped-icons/generic/Dice5";
import { Dice6 } from "../wrapped-icons/generic/Dice6";
import { Door } from "../wrapped-icons/generic/Door";
import { Draft } from "../wrapped-icons/generic/Draft";
import { Edit } from "../wrapped-icons/generic/Edit";
import { Envelope } from "../wrapped-icons/generic/Envelope";
import { EnvelopeOpen } from "../wrapped-icons/generic/EnvelopeOpen";
import { ErrorCircle } from "../wrapped-icons/generic/ErrorCircle";
import { ErrorCircleFilled } from "../wrapped-icons/generic/ErrorCircleFilled";
import { EyeClosed } from "../wrapped-icons/generic/EyeClosed";
import { EyeOpen } from "../wrapped-icons/generic/EyeOpen";
import { EyeSlashed } from "../wrapped-icons/generic/EyeSlashed";
import { FaceHappy } from "../wrapped-icons/generic/FaceHappy";
import { FaceNeutral } from "../wrapped-icons/generic/FaceNeutral";
import { FaceSad } from "../wrapped-icons/generic/FaceSad";
import { FaceVeryHappy } from "../wrapped-icons/generic/FaceVeryHappy";
import { FaceVerySad } from "../wrapped-icons/generic/FaceVerySad";
import { FaceWink } from "../wrapped-icons/generic/FaceWink";
import { Fire } from "../wrapped-icons/generic/Fire";
import { Flag } from "../wrapped-icons/generic/Flag";
import { Flashlight } from "../wrapped-icons/generic/Flashlight";
import { Gear } from "../wrapped-icons/generic/Gear";
import { Glasses } from "../wrapped-icons/generic/Glasses";
import { GraphDown } from "../wrapped-icons/generic/GraphDown";
import { GraphUp } from "../wrapped-icons/generic/GraphUp";
import { Hammer } from "../wrapped-icons/generic/Hammer";
import { Hand } from "../wrapped-icons/generic/Hand";
import { Hashtag } from "../wrapped-icons/generic/Hashtag";
import { History } from "../wrapped-icons/generic/History";
import { Home } from "../wrapped-icons/generic/Home";
import { HomeAlt } from "../wrapped-icons/generic/HomeAlt";
import { Inbox } from "../wrapped-icons/generic/Inbox";
import { InfinityIcon } from "../wrapped-icons/generic/InfinityIcon";
import { InfoCircle } from "../wrapped-icons/generic/InfoCircle";
import { InfoCircleFilled } from "../wrapped-icons/generic/InfoCircleFilled";
import { Jar } from "../wrapped-icons/generic/Jar";
import { KeyIcon } from "../wrapped-icons/generic/KeyIcon";
import { Leaf } from "../wrapped-icons/generic/Leaf";
import { LightBulb } from "../wrapped-icons/generic/LightBulb";
import { LinkChain } from "../wrapped-icons/generic/LinkChain";
import { LinkOff } from "../wrapped-icons/generic/LinkOff";
import { LinkOn } from "../wrapped-icons/generic/LinkOn";
import { LockOff } from "../wrapped-icons/generic/LockOff";
import { LockOn } from "../wrapped-icons/generic/LockOn";
import { Paper } from "../wrapped-icons/generic/Paper";
import { PaperAirplane } from "../wrapped-icons/generic/PaperAirplane";
import { PaperAirplaneAlt } from "../wrapped-icons/generic/PaperAirplaneAlt";
import { Pencil } from "../wrapped-icons/generic/Pencil";
import { PeopleGroup } from "../wrapped-icons/generic/PeopleGroup";
import { PeopleMultiple } from "../wrapped-icons/generic/PeopleMultiple";
import { Percentage } from "../wrapped-icons/generic/Percentage";
import { Person } from "../wrapped-icons/generic/Person";
import { PersonAdd } from "../wrapped-icons/generic/PersonAdd";
import { PersonCheck } from "../wrapped-icons/generic/PersonCheck";
import { PersonRemove } from "../wrapped-icons/generic/PersonRemove";
import { PinIcon } from "../wrapped-icons/generic/PinIcon";
import { Planet } from "../wrapped-icons/generic/Planet";
import { Plant } from "../wrapped-icons/generic/Plant";
import { QuestionCircle } from "../wrapped-icons/generic/QuestionCircle";
import { QuestionCircleFilled } from "../wrapped-icons/generic/QuestionCircleFilled";
import { Radish } from "../wrapped-icons/generic/Radish";
import { Ribbon } from "../wrapped-icons/generic/Ribbon";
import { RockOn } from "../wrapped-icons/generic/RockOn";
import { Schedule } from "../wrapped-icons/generic/Schedule";
import { Scissors } from "../wrapped-icons/generic/Scissors";
import { ScissorsAlt } from "../wrapped-icons/generic/ScissorsAlt";
import { ShareIcon } from "../wrapped-icons/generic/ShareIcon";
import { SignOut } from "../wrapped-icons/generic/SignOut";
import { Slice } from "../wrapped-icons/generic/Slice";
import { Sparkles } from "../wrapped-icons/generic/Sparkles";
import { Stop } from "../wrapped-icons/generic/Stop";
import { StopFilled } from "../wrapped-icons/generic/StopFilled";
import { Tooth } from "../wrapped-icons/generic/Tooth";
import { Box } from "../wrapped-icons/shapes/Box";

const GenericIconCollection = new Map();

// Error State
GenericIconCollection.set("Empty", Box);

GenericIconCollection.set("Air", Air);
GenericIconCollection.set("Alarm", Alarm);
GenericIconCollection.set("AlertCircle", AlertCircle);
GenericIconCollection.set("AlertCircleFilled", AlertCircleFilled);
GenericIconCollection.set("Attach", Attach);
GenericIconCollection.set("Arrow", Arrow);
GenericIconCollection.set("Backspace", Backspace);
GenericIconCollection.set("BackspaceFilled", BackspaceFill);
GenericIconCollection.set("Bell", Bell);
GenericIconCollection.set("Block", Block);
GenericIconCollection.set("Book", Book);
GenericIconCollection.set("BookOpen", BookOpen);
GenericIconCollection.set("Briefcase", Briefcase);
GenericIconCollection.set("Bug", Bug);
GenericIconCollection.set("Cake", Cake);
GenericIconCollection.set("Calculator", Calculator);
GenericIconCollection.set("Calendar", Calendar);
GenericIconCollection.set("Camera", Camera);
GenericIconCollection.set("Check", Check);
GenericIconCollection.set("CheckDouble", CheckDouble);
GenericIconCollection.set("CheckBox", CheckBox);
GenericIconCollection.set("CheckBoxFilled", CheckBoxFilled);
GenericIconCollection.set("CheckCircle", CheckCircle);
GenericIconCollection.set("CheckCircleFilled", CheckCircleFilled);
GenericIconCollection.set("Chess", Chess);
GenericIconCollection.set("Clipboard", Clipboard);
GenericIconCollection.set("Clock", Clock);
GenericIconCollection.set("Cloud", Cloud);
GenericIconCollection.set("Coffee", Coffee);
GenericIconCollection.set("CrossedSwords", CrossedSwords);
GenericIconCollection.set("Crown", Crown);
GenericIconCollection.set("Dice1", Dice1);
GenericIconCollection.set("Dice2", Dice2);
GenericIconCollection.set("Dice3", Dice3);
GenericIconCollection.set("Dice4", Dice4);
GenericIconCollection.set("Dice5", Dice5);
GenericIconCollection.set("Dice6", Dice6);
GenericIconCollection.set("Door", Door);
GenericIconCollection.set("Draft", Draft);
GenericIconCollection.set("Edit", Edit);
GenericIconCollection.set("Envelope", Envelope);
GenericIconCollection.set("EnvelopeOpen", EnvelopeOpen);
GenericIconCollection.set("ErrorCircle", ErrorCircle);
GenericIconCollection.set("ErrorCircleFilled", ErrorCircleFilled);
GenericIconCollection.set("EyeClosed", EyeClosed);
GenericIconCollection.set("EyeOpen", EyeOpen);
GenericIconCollection.set("EyeSlashed", EyeSlashed);
GenericIconCollection.set("FaceHappy", FaceHappy);
GenericIconCollection.set("FaceNeutral", FaceNeutral);
GenericIconCollection.set("FaceSad", FaceSad);
GenericIconCollection.set("FaceVeryHappy", FaceVeryHappy);
GenericIconCollection.set("FaceVerySad", FaceVerySad);
GenericIconCollection.set("FaceWink", FaceWink);
GenericIconCollection.set("Fire", Fire);
GenericIconCollection.set("Flag", Flag);
GenericIconCollection.set("Flashlight", Flashlight);
GenericIconCollection.set("Gear", Gear);
GenericIconCollection.set("Glasses", Glasses);
GenericIconCollection.set("GraphDown", GraphDown);
GenericIconCollection.set("GraphUp", GraphUp);
GenericIconCollection.set("Hammer", Hammer);
GenericIconCollection.set("Hand", Hand);
GenericIconCollection.set("Hashtag", Hashtag);
GenericIconCollection.set("History", History);
GenericIconCollection.set("Home", Home);
GenericIconCollection.set("HomeAlt", HomeAlt);
GenericIconCollection.set("Inbox", Inbox);
GenericIconCollection.set("Infinity", InfinityIcon);
GenericIconCollection.set("InfoCircle", InfoCircle);
GenericIconCollection.set("InfoCircleFilled", InfoCircleFilled);
GenericIconCollection.set("Jar", Jar);
GenericIconCollection.set("Key", KeyIcon);
GenericIconCollection.set("Leaf", Leaf);
GenericIconCollection.set("LightBulb", LightBulb);
GenericIconCollection.set("LinkChain", LinkChain);
GenericIconCollection.set("LinkOff", LinkOff);
GenericIconCollection.set("LinkOn", LinkOn);
GenericIconCollection.set("LockOff", LockOff);
GenericIconCollection.set("LockOn", LockOn);
GenericIconCollection.set("Paper", Paper);
GenericIconCollection.set("PaperAirplane", PaperAirplane);
GenericIconCollection.set("PaperAirplaneAlt", PaperAirplaneAlt);
GenericIconCollection.set("Pencil", Pencil);
GenericIconCollection.set("PeopleGroup", PeopleGroup);
GenericIconCollection.set("PeopleMultiple", PeopleMultiple);
GenericIconCollection.set("Percentage", Percentage);
GenericIconCollection.set("Person", Person);
GenericIconCollection.set("PersonAdd", PersonAdd);
GenericIconCollection.set("PersonCheck", PersonCheck);
GenericIconCollection.set("PersonRemove", PersonRemove);
GenericIconCollection.set("Pin", PinIcon);
GenericIconCollection.set("Planet", Planet);
GenericIconCollection.set("Plant", Plant);
GenericIconCollection.set("QuestionCircle", QuestionCircle);
GenericIconCollection.set("QuestionCircleFilled", QuestionCircleFilled);
GenericIconCollection.set("Radish", Radish);
GenericIconCollection.set("Ribbon", Ribbon);
GenericIconCollection.set("RockOn", RockOn);
GenericIconCollection.set("Schedule", Schedule);
GenericIconCollection.set("Scissors", Scissors);
GenericIconCollection.set("ScissorsAlt", ScissorsAlt);
GenericIconCollection.set("Share", ShareIcon);
GenericIconCollection.set("SignOut", SignOut);
GenericIconCollection.set("Slice", Slice);
GenericIconCollection.set("Sparkles", Sparkles);
GenericIconCollection.set("Stop", Stop);
GenericIconCollection.set("StopFilled", StopFilled);
GenericIconCollection.set("Tooth", Tooth);

export { GenericIconCollection };
