import { Air } from "../wrapped-icons/Air";
import { AirplayAudio } from "../wrapped-icons/AirplayAudio";
import { AirplayVideo } from "../wrapped-icons/AirplayVideo";
import { Airpods } from "../wrapped-icons/Airpods";
import { AlignBottom } from "../wrapped-icons/AlignBottom";
import { Alarm } from "../wrapped-icons/Alarm";
import { AlignHorizontalCenter } from "../wrapped-icons/AlignHorizontalCenter";
import { AlignLeft } from "../wrapped-icons/AlignLeft";
import { AlignRight } from "../wrapped-icons/AlignRight";
import { AlignTop } from "../wrapped-icons/AlignTop";
import { AlignToBottom } from "../wrapped-icons/AlignToBottom";
import { AlignToMiddle } from "../wrapped-icons/AlignToMiddle";
import { AlignVerticalCenter } from "../wrapped-icons/AlignVerticalCenter";
import { AndroidFill } from "../wrapped-icons/AndroidFill";
import { AngularFill } from "../wrapped-icons/AngularFill";
import { ArrowBackThick } from "../wrapped-icons/ArrowBackThick";
import { ArrowBack } from "../wrapped-icons/ArrowBack";
import { ArrowBackThickFill } from "../wrapped-icons/ArrowBackThickFill";
import { ArrowClockwise } from "../wrapped-icons/ArrowClockwise";
import { ArrowCounterClockwise } from "../wrapped-icons/ArrowCounterClockwise";
import { ArrowCycle } from "../wrapped-icons/ArrowCycle";
import { ArrowDown } from "../wrapped-icons/ArrowDown";
import { ArrowDownLeft } from "../wrapped-icons/ArrowDownLeft";
import { ArrowDownRight } from "../wrapped-icons/ArrowDownRight";
import { ArrowDownThick } from "../wrapped-icons/ArrowDownThick";
import { ArrowUpThick } from "../wrapped-icons/ArrowUpThick";
import { ArrowUpRight } from "../wrapped-icons/ArrowUpRight";
import { ArrowForwardThick } from "../wrapped-icons/ArrowForwardThick";
import { ArrowForwardThickFill } from "../wrapped-icons/ArrowForwardThickFill";
import { ArrowLeft } from "../wrapped-icons/ArrowLeft";
import { ArrowLeftThick } from "../wrapped-icons/ArrowLeftThick";
import { ArrowUpLeft } from "../wrapped-icons/ArrowUpLeft";
import { ArrowUpDown } from "../wrapped-icons/ArrowUpDown";
import { ArrowUp } from "../wrapped-icons/ArrowUp";
import { ArrowShuffle } from "../wrapped-icons/ArrowShuffle";
import { ArrowRightThick } from "../wrapped-icons/ArrowRightThick";
import { ArrowRightLeft } from "../wrapped-icons/ArrowRightLeft";
import { ArrowRight } from "../wrapped-icons/ArrowRight";
import { ArrowForward } from "../wrapped-icons/ArrowForward";
import { ArrowRepeat } from "../wrapped-icons/ArrowRepeat";
import { AlignToTop } from "../wrapped-icons/AlignToTop";

const GenericIconCollection = new Map();

GenericIconCollection.set("Air", Air);
GenericIconCollection.set("AirplayAudio", AirplayAudio);
GenericIconCollection.set("AirplayVideo", AirplayVideo);
GenericIconCollection.set("Airpods", Airpods);
GenericIconCollection.set("Alarm", Alarm);
GenericIconCollection.set("AlignBottom", AlignBottom);
GenericIconCollection.set("AlignHorizontalCenter", AlignHorizontalCenter);
GenericIconCollection.set("AlignLeft", AlignLeft);
GenericIconCollection.set("AlignRight", AlignRight);
GenericIconCollection.set("AlignTop", AlignTop);
GenericIconCollection.set("AlignToBottom", AlignToBottom);
GenericIconCollection.set("AlignToTop", AlignToTop);
GenericIconCollection.set("AlignToMiddle", AlignToMiddle);
GenericIconCollection.set("AlignVerticalCenter", AlignVerticalCenter);

GenericIconCollection.set("ArrowBack", ArrowBack);
GenericIconCollection.set("ArrowBackThick", ArrowBackThick);
GenericIconCollection.set("ArrowBackThickFill", ArrowBackThickFill);
GenericIconCollection.set("ArrowClockwise", ArrowClockwise);
GenericIconCollection.set("ArrowCounterClockwise", ArrowCounterClockwise);
GenericIconCollection.set("ArrowCycle", ArrowCycle);
GenericIconCollection.set("ArrowDown", ArrowDown);
GenericIconCollection.set("ArrowDownLeft", ArrowDownLeft);
GenericIconCollection.set("ArrowDownRight", ArrowDownRight);
GenericIconCollection.set("ArrowDownThick", ArrowDownThick);
GenericIconCollection.set("ArrowForward", ArrowForward);
GenericIconCollection.set("ArrowForwardThick", ArrowForwardThick);
GenericIconCollection.set("ArrowForwardThickFill", ArrowForwardThickFill);
GenericIconCollection.set("ArrowLeft", ArrowLeft);
GenericIconCollection.set("ArrowLeftThick", ArrowLeftThick);
GenericIconCollection.set("ArrowRepeat", ArrowRepeat);
GenericIconCollection.set("ArrowRight", ArrowRight);
GenericIconCollection.set("ArrowRightLeft", ArrowRightLeft);
GenericIconCollection.set("ArrowRightThick", ArrowRightThick);
GenericIconCollection.set("ArrowShuffle", ArrowShuffle);
GenericIconCollection.set("ArrowUpDown", ArrowUpDown);
GenericIconCollection.set("ArrowUp", ArrowUp);
GenericIconCollection.set("ArrowUpLeft", ArrowUpLeft);
GenericIconCollection.set("ArrowUpRight", ArrowUpRight);
GenericIconCollection.set("ArrowUpThick", ArrowUpThick);

export { GenericIconCollection };
