import { Behance } from "../wrapped-icons/brand/Behance";
import { Discord } from "../wrapped-icons/brand/Discord";
import { Dribble } from "../wrapped-icons/brand/Dribble";
import { Dropbox } from "../wrapped-icons/brand/Dropbox";
import { Facebook } from "../wrapped-icons/brand/Facebook";
import { Figma } from "../wrapped-icons/brand/Figma";
import { Gatsby } from "../wrapped-icons/brand/Gatsby";
import { Google } from "../wrapped-icons/brand/Google";
import { GoogleCircle } from "../wrapped-icons/brand/GoogleCircle";
import { Instagram } from "../wrapped-icons/brand/Instagram";
import { LinkedIn } from "../wrapped-icons/brand/LinkedIn";
import { LinkedInBox } from "../wrapped-icons/brand/LinkedInBox";
import { Mastodon } from "../wrapped-icons/brand/Mastodon";
import { Medium } from "../wrapped-icons/brand/Medium";
import { Pinterest } from "../wrapped-icons/brand/Pinterest";
import { Reddit } from "../wrapped-icons/brand/Reddit";
import { SlackLogo } from "../wrapped-icons/brand/Slack";
import { Snapchat } from "../wrapped-icons/brand/Snapchat";
import { Soundcloud } from "../wrapped-icons/brand/Soundcloud";
import { Spotify } from "../wrapped-icons/brand/Spotify";
import { TelegramLogo } from "../wrapped-icons/brand/TelegramLogo";
import { TikTokFill } from "../wrapped-icons/brand/TikTokFill";
import { TwitchFill } from "../wrapped-icons/brand/TwitchFill";
import { Twitter } from "../wrapped-icons/brand/Twitter";
import { UnsplashFill } from "../wrapped-icons/brand/UnsplashFill";
import { VimeoFill } from "../wrapped-icons/brand/VimeoFill";
import { WhatsAppFill } from "../wrapped-icons/brand/WhatsAppFill";
import { YelpFill } from "../wrapped-icons/brand/YelpFill";
import { YouTubeFill } from "../wrapped-icons/brand/YouTubeFill";
import { Box } from "../wrapped-icons/shapes/Box";

const BrandIconCollection = new Map();

BrandIconCollection.set("Empty", Box);

BrandIconCollection.set("Behance", Behance);
BrandIconCollection.set("Discord", Discord);
BrandIconCollection.set("Dribble", Dribble);
BrandIconCollection.set("Dropbox", Dropbox);
BrandIconCollection.set("Facebook", Facebook);
BrandIconCollection.set("Figma", Figma);
BrandIconCollection.set("Gatsby", Gatsby);
BrandIconCollection.set("Google", Google);
BrandIconCollection.set("GoogleCircle", GoogleCircle);
BrandIconCollection.set("Instagram", Instagram);
BrandIconCollection.set("LinkedIn", LinkedIn);
BrandIconCollection.set("LinkedInBox", LinkedInBox);
BrandIconCollection.set("Mastodon", Mastodon);
BrandIconCollection.set("Medium", Medium);
BrandIconCollection.set("Pinterest", Pinterest);
BrandIconCollection.set("Reddit", Reddit);
BrandIconCollection.set("Slack", SlackLogo);
BrandIconCollection.set("Snapchat", Snapchat);
BrandIconCollection.set("Soundcloud", Soundcloud);
BrandIconCollection.set("Spotify", Spotify);
BrandIconCollection.set("Telegram", TelegramLogo);
BrandIconCollection.set("Twitter", Twitter);
BrandIconCollection.set("TikTok", TikTokFill);
BrandIconCollection.set("Twitch", TwitchFill);
BrandIconCollection.set("Unsplash", UnsplashFill);
BrandIconCollection.set("Vimeo", VimeoFill);
BrandIconCollection.set("WhatsApp", WhatsAppFill);
BrandIconCollection.set("Yelp", YelpFill);
BrandIconCollection.set("YouTube", YouTubeFill);

export { BrandIconCollection };
