import { Box } from "../wrapped-icons/shapes/Box";
import { BoxFilled } from "../wrapped-icons/shapes/BoxFilled";
import { Circle } from "../wrapped-icons/shapes/Circle";
import { CircleFilled } from "../wrapped-icons/shapes/CircleFilled";
import { Cross } from "../wrapped-icons/shapes/Cross";
import { Diamond } from "../wrapped-icons/shapes/Diamond";
import { EqualCircle } from "../wrapped-icons/shapes/EqualCircle";
import { EqualCircleFilled } from "../wrapped-icons/shapes/EqualCircleFilled";
import { Heart } from "../wrapped-icons/shapes/Heart";
import { HeartFilled } from "../wrapped-icons/shapes/HeartFilled";
import { Heptagon } from "../wrapped-icons/shapes/Heptagon";
import { HeptagonFilled } from "../wrapped-icons/shapes/HeptagonFilled";
import { Hexagon } from "../wrapped-icons/shapes/Hexagon";
import { HexagonFilled } from "../wrapped-icons/shapes/HexagonFilled";
import { MinusIcon } from "../wrapped-icons/shapes/Minus";
import { MinusCircle } from "../wrapped-icons/shapes/MinusCircle";
import { MinusCircleFilled } from "../wrapped-icons/shapes/MinusCircleFilled";
import { Moon } from "../wrapped-icons/shapes/Moon";
import { MoonFilled } from "../wrapped-icons/shapes/MoonFilled";
import { Octagon } from "../wrapped-icons/shapes/Octagon";
import { OctagonFilled } from "../wrapped-icons/shapes/OctagonFilled";
import { Oval } from "../wrapped-icons/shapes/Oval";
import { OvalFilled } from "../wrapped-icons/shapes/OvalFilled";
import { Parallelogram } from "../wrapped-icons/shapes/Parallelogram";
import { ParallelogramFilled } from "../wrapped-icons/shapes/ParallelogramFilled";
import { Pentagon } from "../wrapped-icons/shapes/Pentagon";
import { PentagonFilled } from "../wrapped-icons/shapes/PentagonFilled";
import { PlusIcon } from "../wrapped-icons/shapes/Plus";
import { PlusCircle } from "../wrapped-icons/shapes/PlusCircle";
import { PlusCircleFilled } from "../wrapped-icons/shapes/PlusCircleFilled";

const ShapeIconCollection = new Map();

ShapeIconCollection.set("Empty", Box);
ShapeIconCollection.set("Box", Box);
ShapeIconCollection.set("BoxFilled", BoxFilled);
ShapeIconCollection.set("Circle", Circle);
ShapeIconCollection.set("CircleFilled", CircleFilled);
ShapeIconCollection.set("Cross", Cross);
ShapeIconCollection.set("Diamond", Diamond);
ShapeIconCollection.set("EqualCircle", EqualCircle);
ShapeIconCollection.set("EqualCircleFilled", EqualCircleFilled);
ShapeIconCollection.set("Heart", Heart);
ShapeIconCollection.set("HeartFilled", HeartFilled);
ShapeIconCollection.set("Heptagon", Heptagon);
ShapeIconCollection.set("HeptagonFilled", HeptagonFilled);
ShapeIconCollection.set("Hexagon", Hexagon);
ShapeIconCollection.set("HexagonFilled", HexagonFilled);
ShapeIconCollection.set("Minus", MinusIcon);
ShapeIconCollection.set("MinusCircle", MinusCircle);
ShapeIconCollection.set("MinusCircleFilled", MinusCircleFilled);
ShapeIconCollection.set("Moon", Moon);
ShapeIconCollection.set("MoonFilled", MoonFilled);
ShapeIconCollection.set("Octagon", Octagon);
ShapeIconCollection.set("OctagonFilled", OctagonFilled);
ShapeIconCollection.set("Oval", Oval);
ShapeIconCollection.set("OvalFilled", OvalFilled);
ShapeIconCollection.set("Parallelogram", Parallelogram);
ShapeIconCollection.set("ParallelogramFilled", ParallelogramFilled);
ShapeIconCollection.set("Plus", PlusIcon);
ShapeIconCollection.set("PlusCircle", PlusCircle);
ShapeIconCollection.set("PlusCircleFilled", PlusCircleFilled);
ShapeIconCollection.set("Pentagon", Pentagon);
ShapeIconCollection.set("PentagonFilled", PentagonFilled);

export { ShapeIconCollection };
