import { Box } from "../wrapped-icons/shapes/Box";
import { Circle } from "../wrapped-icons/shapes/Circle";
import { CircleFilled } from "../wrapped-icons/shapes/CircleFilled";
import { MinusCircle } from "../wrapped-icons/shapes/MinusCircle";
import { MinusCircleFilled } from "../wrapped-icons/shapes/MinusCircleFilled";
import { PlusCircle } from "../wrapped-icons/shapes/PlusCircle";
import { PlusCircleFilled } from "../wrapped-icons/shapes/PlusCircleFilled";
import { Cross } from "../wrapped-icons/shapes/Cross";
import { Diamond } from "../wrapped-icons/shapes/Diamond";
import { EqualCircle } from "../wrapped-icons/shapes/EqualCircle";
import { EqualCircleFilled } from "../wrapped-icons/shapes/EqualCircleFilled";
import { BoxFilled } from "../wrapped-icons/shapes/BoxFilled";
import { Heptagon } from "../wrapped-icons/shapes/Heptagon";
import { HeptagonFilled } from "../wrapped-icons/shapes/HeptagonFilled";
import { Hexagon } from "../wrapped-icons/shapes/Hexagon";
import { HexagonFilled } from "../wrapped-icons/shapes/HexagonFilled";
import { Heart } from "../wrapped-icons/shapes/Heart";
import { HeartFilled } from "../wrapped-icons/shapes/HeartFilled";

const ShapeIconCollection = new Map();

ShapeIconCollection.set("Empty", Box);
ShapeIconCollection.set("Box", Box);
ShapeIconCollection.set("BoxFilled", BoxFilled);
ShapeIconCollection.set("Circle", Circle);
ShapeIconCollection.set("CircleFilled", CircleFilled);
ShapeIconCollection.set("Cross", Cross);
ShapeIconCollection.set("Diamond", Diamond);
ShapeIconCollection.set("EqualCircle", EqualCircle);
ShapeIconCollection.set("EqualCircleFilled", EqualCircleFilled);
ShapeIconCollection.set("Heart", Heart);
ShapeIconCollection.set("HeartFilled", HeartFilled);
ShapeIconCollection.set("Heptagon", Heptagon);
ShapeIconCollection.set("HeptagonFilled", HeptagonFilled);
ShapeIconCollection.set("Hexagon", Hexagon);
ShapeIconCollection.set("HexagonFilled", HexagonFilled);
ShapeIconCollection.set("MinusCircle", MinusCircle);
ShapeIconCollection.set("MinusCircleFilled", MinusCircleFilled);
ShapeIconCollection.set("PlusCircle", PlusCircle);
ShapeIconCollection.set("PlusCircleFilled", PlusCircleFilled);

export { ShapeIconCollection };
