import { AlignBottom } from "../wrapped-icons/direction/AlignBottom";
import { AlignHorizontalCenter } from "../wrapped-icons/direction/AlignHorizontalCenter";
import { AlignLeft } from "../wrapped-icons/direction/AlignLeft";
import { AlignRight } from "../wrapped-icons/direction/AlignRight";
import { AlignToBottom } from "../wrapped-icons/direction/AlignToBottom";
import { AlignToMiddle } from "../wrapped-icons/direction/AlignToMiddle";
import { AlignTop } from "../wrapped-icons/direction/AlignTop";
import { AlignToTop } from "../wrapped-icons/direction/AlignToTop";
import { AlignVerticalCenter } from "../wrapped-icons/direction/AlignVerticalCenter";
import { Ascending } from "../wrapped-icons/direction/Ascending";
import { CaretCircleDown } from "../wrapped-icons/direction/CaretCircleDown";
import { CaretCircleDownFilled } from "../wrapped-icons/direction/CaretCircleDownFilled";
import { CaretCircleLeft } from "../wrapped-icons/direction/CaretCircleLeft";
import { CaretCircleLeftFilled } from "../wrapped-icons/direction/CaretCircleLeftFilled";
import { CaretCircleRight } from "../wrapped-icons/direction/CaretCircleRight";
import { CaretCircleRightFilled } from "../wrapped-icons/direction/CaretCircleRightFilled";
import { CaretCircleUp } from "../wrapped-icons/direction/CaretCircleUp";
import { CaretCircleUpFilled } from "../wrapped-icons/direction/CaretCircleUpFilled";
import { ChevronCircleDown } from "../wrapped-icons/direction/ChevronCircleDown";
import { ChevronCircleDownFilled } from "../wrapped-icons/direction/ChevronCircleDownFilled";
import { ChevronCircleLeft } from "../wrapped-icons/direction/ChevronCircleLeft";
import { ChevronCircleLeftFilled } from "../wrapped-icons/direction/ChevronCircleLeftFilled";
import { ChevronCircleRight } from "../wrapped-icons/direction/ChevronCircleRight";
import { ChevronCircleRightFilled } from "../wrapped-icons/direction/ChevronCircleRightFilled";
import { ChevronCircleUp } from "../wrapped-icons/direction/ChevronCircleUp";
import { ChevronCircleUpFilled } from "../wrapped-icons/direction/ChevronCircleUpFilled";
import { ChevronDown } from "../wrapped-icons/direction/ChevronDown";
import { ChevronDownSmall } from "../wrapped-icons/direction/ChevronDownSmall";
import { ChevronHorizontal } from "../wrapped-icons/direction/ChevronHorizontal";
import { ChevronLeft } from "../wrapped-icons/direction/ChevronLeft";
import { ChevronLeftSmall } from "../wrapped-icons/direction/ChevronLeftSmall";
import { ChevronRight } from "../wrapped-icons/direction/ChevronRight";
import { ChevronRightSmall } from "../wrapped-icons/direction/ChevronRightSmall";
import { ChevronUp } from "../wrapped-icons/direction/ChevronUp";
import { ChevronUpSmall } from "../wrapped-icons/direction/ChevronUpSmall";
import { ChevronVertical } from "../wrapped-icons/direction/ChevronVertical";
import { Descending } from "../wrapped-icons/direction/Descending";
import { PanelBottom } from "../wrapped-icons/direction/PanelBottom";
import { PanelLeft } from "../wrapped-icons/direction/PanelLeft";
import { PanelRight } from "../wrapped-icons/direction/PanelRight";
import { PanelSplit } from "../wrapped-icons/direction/PanelSplit";
import { PanelSplitColumn } from "../wrapped-icons/direction/PanelSplitColumn";
import { PanelSplitRow } from "../wrapped-icons/direction/PanelSplitRow";
import { PanelTop } from "../wrapped-icons/direction/PanelTop";
import { PointerDownFilled } from "../wrapped-icons/direction/PointerDownFilled";
import { PointerHand } from "../wrapped-icons/direction/PointerHand";
import { PointerLeftFilled } from "../wrapped-icons/direction/PointerLeftFilled";
import { PointerRightFilled } from "../wrapped-icons/direction/PointerRightFilled";
import { PointerUp } from "../wrapped-icons/direction/PointerUp";
import { PointerUpFilled } from "../wrapped-icons/direction/PointerUpFilled";
import { SidebarLeft } from "../wrapped-icons/direction/SidebarLeft";
import { SidebarRight } from "../wrapped-icons/direction/SidebarRight";
import { SortIcon } from "../wrapped-icons/direction/SortIcon";
import { TextAlignCenter } from "../wrapped-icons/direction/TextAlignCenter";
import { TextAlignJustify } from "../wrapped-icons/direction/TextAlignJustify";
import { TextAlignLeft } from "../wrapped-icons/direction/TextAlignLeft";
import { TextAlignRight } from "../wrapped-icons/direction/TextAlignRight";
import { Box } from "../wrapped-icons/shapes/Box";

const DirectionIconCollection = new Map();

DirectionIconCollection.set("Empty", Box);

DirectionIconCollection.set("AlignHorizontalCenter", AlignHorizontalCenter);
DirectionIconCollection.set("AlignVerticalCenter", AlignVerticalCenter);
DirectionIconCollection.set("AlignBottom", AlignBottom);
DirectionIconCollection.set("AlignLeft", AlignLeft);
DirectionIconCollection.set("AlignRight", AlignRight);
DirectionIconCollection.set("AlignToBottom", AlignToBottom);
DirectionIconCollection.set("AlignToMiddle", AlignToMiddle);
DirectionIconCollection.set("AlignToTop", AlignToTop);
DirectionIconCollection.set("AlignTop", AlignTop);
DirectionIconCollection.set("Ascending", Ascending);
DirectionIconCollection.set("CaretCircleDown", CaretCircleDown);
DirectionIconCollection.set("CaretCircleDownFilled", CaretCircleDownFilled);
DirectionIconCollection.set("CaretCircleLeft", CaretCircleLeft);
DirectionIconCollection.set("CaretCircleLeftFilled", CaretCircleLeftFilled);
DirectionIconCollection.set("CaretCircleRight", CaretCircleRight);
DirectionIconCollection.set("CaretCircleRightFilled", CaretCircleRightFilled);
DirectionIconCollection.set("CaretCircleUp", CaretCircleUp);
DirectionIconCollection.set("CaretCircleUpFilled", CaretCircleUpFilled);
DirectionIconCollection.set("ChevronCircleLeft", ChevronCircleLeft);
DirectionIconCollection.set("ChevronCircleLeftFilled", ChevronCircleLeftFilled);
DirectionIconCollection.set("ChevronCircleRight", ChevronCircleRight);
DirectionIconCollection.set(
  "ChevronCircleRightFilled",
  ChevronCircleRightFilled,
);
DirectionIconCollection.set("ChevronCircleUp", ChevronCircleUp);
DirectionIconCollection.set("ChevronCircleUpFilled", ChevronCircleUpFilled);
DirectionIconCollection.set("ChevronCircleDown", ChevronCircleDown);
DirectionIconCollection.set("ChevronCircleDownFilled", ChevronCircleDownFilled);
DirectionIconCollection.set("ChevronDown", ChevronDown);
DirectionIconCollection.set("ChevronDownSmall", ChevronDownSmall);
DirectionIconCollection.set("ChevronHorizontal", ChevronHorizontal);
DirectionIconCollection.set("ChevronLeft", ChevronLeft);
DirectionIconCollection.set("ChevronLeftSmall", ChevronLeftSmall);
DirectionIconCollection.set("ChevronRight", ChevronRight);
DirectionIconCollection.set("ChevronRightSmall", ChevronRightSmall);
DirectionIconCollection.set("ChevronUp", ChevronUp);
DirectionIconCollection.set("ChevronUpSmall", ChevronUpSmall);
DirectionIconCollection.set("ChevronVertical", ChevronVertical);
DirectionIconCollection.set("Descending", Descending);
DirectionIconCollection.set("PanelBottom", PanelBottom);
DirectionIconCollection.set("PanelLeft", PanelLeft);
DirectionIconCollection.set("PanelRight", PanelRight);
DirectionIconCollection.set("PanelSplit", PanelSplit);
DirectionIconCollection.set("PanelSplitRow", PanelSplitRow);
DirectionIconCollection.set("PanelSplitColumn", PanelSplitColumn);
DirectionIconCollection.set("PanelTop", PanelTop);
DirectionIconCollection.set("PointerDownFilled", PointerDownFilled);
DirectionIconCollection.set("PointerHand", PointerHand);
DirectionIconCollection.set("PointerLeftFilled", PointerLeftFilled);
DirectionIconCollection.set("PointerRightFilled", PointerRightFilled);
DirectionIconCollection.set("PointerUp", PointerUp);
DirectionIconCollection.set("PointerUpFilled", PointerUpFilled);
DirectionIconCollection.set("SidebarLeft", SidebarLeft);
DirectionIconCollection.set("SidebarRight", SidebarRight);
DirectionIconCollection.set("Sort", SortIcon);
DirectionIconCollection.set("TextAlignCenter", TextAlignCenter);
DirectionIconCollection.set("TextAlignLeft", TextAlignLeft);
DirectionIconCollection.set("TextAlignJustify", TextAlignJustify);
DirectionIconCollection.set("TextAlignRight", TextAlignRight);

export { DirectionIconCollection };
