import {
  BrandIconName,
  GenericIconName,
  NavigationIconName,
  TechnologyIconName,
  MediaIconName,
  MessagingIconName,
  EcomIconName,
  DirectionIconName,
  TransportationIconName,
  ShapeIconName,
} from "@nmportfolio/core";

export const brandIconNames: BrandIconName[] = [
  "Behance",
  "Facebook",
  "Instagram",
  "Twitter",
  "TikTok",
  "Twitch",
  "Unsplash",
  "Vimeo",
  "WhatsApp",
  "Yelp",
  "YouTube",
];

export const directionIconNames: DirectionIconName[] = [
  "AlignHorizontalCenter",
  "AlignVerticalCenter",
  "AlignBottom",
  "AlignTop",
  "AlignLeft",
  "AlignRight",
  "AlignToBottom",
  "AlignToMiddle",
  "AlignToTop",
  "Ascending",
  "CaretCircleDown",
  "CaretCircleDownFilled",
  "CaretCircleLeft",
  "CaretCircleLeftFilled",
  "CaretCircleRight",
  "CaretCircleRightFilled",
  "CaretCircleUp",
  "CaretCircleUpFilled",
  "ChevronCircleDown",
  "ChevronCircleDownFilled",
  "ChevronCircleLeft",
  "ChevronCircleLeftFilled",
  "ChevronCircleRight",
  "ChevronCircleRightFilled",
  "ChevronCircleUp",
  "ChevronCircleUpFilled",
  "ChevronDown",
  "ChevronDownSmall",
  "ChevronHorizontal",
  "ChevronLeft",
  "ChevronLeftSmall",
  "ChevronRight",
  "ChevronRightSmall",
  "ChevronUp",
  "ChevronUpSmall",
  "ChevronVertical",
];

export const ecomIconNames: EcomIconName[] = [
  "Bank",
  "Basket",
  "Bitcoin",
  "Cart",
];

export const genericIconNames: GenericIconName[] = [
  "Air",
  "Alarm",
  "Attach",
  "Backspace",
  "BackspaceFilled",
  "Bell",
  "Block",
  "Book",
  "BookOpen",
  "Briefcase",
  "Bug",
  "Cake",
  "Calculator",
  "Calendar",
  "Camera",
  "Check",
  "CheckBox",
  "CheckBoxFilled",
  "CheckCircle",
  "CheckCircleFilled",
  "Chess",
  "ErrorCircle",
  "ErrorCircleFilled",
];

export const mediaIconNames: MediaIconName[] = [
  "AirplayAudio",
  "AirplayVideo",
  "Airpods",
];

export const messagingIconNames: MessagingIconName[] = [
  "ChatAdd",
  "ChatApprove",
  "ChatBubble",
  "ChatDots",
  "ChatError",
  "ChatQuestion",
  "ChatReject",
  "ChatRemove",
];

export const navigationIconNames: NavigationIconName[] = [
  "ArrowBack",
  "ArrowBackThickFilled",
  "ArrowBackThick",
  "ArrowClockwise",
  "ArrowCounterClockwise",
  "ArrowCycle",
  "ArrowDown",
  "ArrowDownLeft",
  "ArrowDownRight",
  "ArrowDownThick",
  "ArrowForward",
  "ArrowForwardThickFilled",
  "ArrowForwardThick",
  "ArrowLeft",
  "ArrowLeftThick",
  "ArrowRepeat",
  "ArrowRight",
  "ArrowRightLeft",
  "ArrowRightThick",
  "ArrowShuffle",
  "ArrowUp",
  "ArrowUpDown",
  "ArrowUpLeft",
  "ArrowUpRight",
  "ArrowUpThick",
];

export const shapeIconNames: ShapeIconName[] = [
  "Box",
  "Circle",
  "CircleFilled",
  "MinusCircle",
  "MinusCircleFilled",
  "PlusCircle",
  "PlusCircleFilled",
];

export const technologyIconNames: TechnologyIconName[] = [
  "Django",
  "Bluetooth",
  "Android",
  "AugmentedReality",
  "BatteryCharging",
  "BatteryEmpty",
  "BatteryFull",
  "BatteryLow",
  "BatteryMedium",
  "Bootstrap",
  "Bluetooth",
  "Angular",
  "Github",
  "PHP",
  "RSS",
  "TypeScript",
  "Vercel",
  "Vue",
  "Yarn",
];

export const transportationIconName: TransportationIconName[] = [
  "Bicycle",
  "Boat",
  "MapPin",
];
