import { Box } from "../wrapped-icons/shapes/Box";
import { AndroidFill } from "../wrapped-icons/technology/AndroidFill";
import { AngularFill } from "../wrapped-icons/technology/AngularFill";
import { AugmentedReality } from "../wrapped-icons/technology/AugmentedReality";
import { BatteryCharging } from "../wrapped-icons/technology/BatteryCharging";
import { BatteryEmpty } from "../wrapped-icons/technology/BatteryEmpty";
import { BatteryFull } from "../wrapped-icons/technology/BatteryFull";
import { BatteryLow } from "../wrapped-icons/technology/BatteryLow";
import { BatteryMedium } from "../wrapped-icons/technology/BatteryMedium";
import { Bluetooth } from "../wrapped-icons/technology/Bluetooth";
import { BootstrapFill } from "../wrapped-icons/technology/BootstrapFill";
import { Codepen } from "../wrapped-icons/technology/Codepen";
import { CommandIcon } from "../wrapped-icons/technology/Command";
import { Computing } from "../wrapped-icons/technology/Computing";
import { Copy } from "../wrapped-icons/technology/Copy";
import { CSS } from "../wrapped-icons/technology/CSS";
import { Dashboard } from "../wrapped-icons/technology/Dashboard";
import { Data } from "../wrapped-icons/technology/Data";
import { Devices } from "../wrapped-icons/technology/Devices";
import { DjangoFill } from "../wrapped-icons/technology/DjangoFill";
import { DownloadIcon } from "../wrapped-icons/technology/Download";
import { DownloadAlt } from "../wrapped-icons/technology/DownloadAlt";
import { File } from "../wrapped-icons/technology/File";
import { Filter } from "../wrapped-icons/technology/Filter";
import { Folder } from "../wrapped-icons/technology/Folder";
import { FolderAdd } from "../wrapped-icons/technology/FolderAdd";
import { GameController } from "../wrapped-icons/technology/GameController";
import { GithubFill } from "../wrapped-icons/technology/GithubFill";
import { GraphQL } from "../wrapped-icons/technology/GraphQL";
import { HTMLIcon } from "../wrapped-icons/technology/HTMLIcon";
import { Image } from "../wrapped-icons/technology/Image";
import { JavaScriptIcon } from "../wrapped-icons/technology/JavaScriptIcon";
import { JQuery } from "../wrapped-icons/technology/JQuery";
import { KeyCap } from "../wrapped-icons/technology/KeyCap";
import { Laptop } from "../wrapped-icons/technology/Laptop";
import { MobileDevice } from "../wrapped-icons/technology/MobileDevice";
import { Monitor } from "../wrapped-icons/technology/Monitor";
import { PHPFill } from "../wrapped-icons/technology/PHPFill";
import { RssFill } from "../wrapped-icons/technology/RssFill";
import { TypeScriptFill } from "../wrapped-icons/technology/TypeScriptFill";
import { Upload } from "../wrapped-icons/technology/Upload";
import { VercelFill } from "../wrapped-icons/technology/VercelFill";
import { VueFill } from "../wrapped-icons/technology/VueFill";
import { YarnFill } from "../wrapped-icons/technology/YarnFill";

const TechnologyIconCollection = new Map();

// Error State Box
TechnologyIconCollection.set("Empty", Box);

TechnologyIconCollection.set("Android", AndroidFill);
TechnologyIconCollection.set("Angular", AngularFill);
TechnologyIconCollection.set("AugmentedReality", AugmentedReality);
TechnologyIconCollection.set("Bootstrap", BootstrapFill);
TechnologyIconCollection.set("BatteryCharging", BatteryCharging);
TechnologyIconCollection.set("BatteryEmpty", BatteryEmpty);
TechnologyIconCollection.set("BatteryFull", BatteryFull);
TechnologyIconCollection.set("BatteryLow", BatteryLow);
TechnologyIconCollection.set("BatteryMedium", BatteryMedium);
TechnologyIconCollection.set("Bluetooth", Bluetooth);
TechnologyIconCollection.set("Bootstrap", BootstrapFill);
TechnologyIconCollection.set("Codepen", Codepen);
TechnologyIconCollection.set("Command", CommandIcon);
TechnologyIconCollection.set("Computing", Computing);
TechnologyIconCollection.set("Copy", Copy);
TechnologyIconCollection.set("CSS", CSS);
TechnologyIconCollection.set("Dashboard", Dashboard);
TechnologyIconCollection.set("Data", Data);
TechnologyIconCollection.set("Devices", Devices);
TechnologyIconCollection.set("Django", DjangoFill);
TechnologyIconCollection.set("Download", DownloadIcon);
TechnologyIconCollection.set("DownloadAlt", DownloadAlt);
TechnologyIconCollection.set("File", File);
TechnologyIconCollection.set("Filter", Filter);
TechnologyIconCollection.set("Folder", Folder);
TechnologyIconCollection.set("FolderAdd", FolderAdd);
TechnologyIconCollection.set("GameController", GameController);
TechnologyIconCollection.set("Github", GithubFill);
TechnologyIconCollection.set("GraphQL", GraphQL);
TechnologyIconCollection.set("HTML", HTMLIcon);
TechnologyIconCollection.set("Image", Image);
TechnologyIconCollection.set("JavaScript", JavaScriptIcon);
TechnologyIconCollection.set("JQuery", JQuery);
TechnologyIconCollection.set("KeyCap", KeyCap);
TechnologyIconCollection.set("Laptop", Laptop);
TechnologyIconCollection.set("MobileDevice", MobileDevice);
TechnologyIconCollection.set("Monitor", Monitor);
TechnologyIconCollection.set("PHP", PHPFill);
TechnologyIconCollection.set("RSS", RssFill);
TechnologyIconCollection.set("TypeScript", TypeScriptFill);
TechnologyIconCollection.set("Upload", Upload);
TechnologyIconCollection.set("Vercel", VercelFill);
TechnologyIconCollection.set("Vue", VueFill);
TechnologyIconCollection.set("Yarn", YarnFill);

export { TechnologyIconCollection };
